default_orientation:
  default: horizontal
  type: enum
  choices:
    - horizontal
    - vertical

default_position:
  default: 50
  type: integer
  min: 0
  max: 100

default_handle_style:
  default: default
  type: enum
  choices:
    - default
    - circle
    - thin
    - grabber

default_handle_color:
  default: ""
  type: string

default_label_position:
  default: end
  type: enum
  choices:
    - start
    - center
    - end

default_show_labels:
  default: true
  type: bool



